### ISSUE TITLE
OPACoders organization is going to be deleted.

### ISSUE THREAD

**Issue by jgeis** [smaltin-rules/smaltin-rules.github.io#7]
@smaltin-rules As the owner of OPACoders organization on Github, I have decided to delete it since it was inactive. Please send me a comment when you'd like to get the data. When downloaded, mark this closed.

-- Joseph 😀

**Comment by jgeis** [comment]
There was no other way than snail email. 😃

**Comment by smaltin-rules** [comment]
I would like the data.

**Comment by jgeis** [comment]
https://drive.google.com/file/d/0Bw-OBhsmmEz5N2VtRVNEdjN4Ukk/view?usp=sharing
and
https://drive.google.com/file/d/0Bw-OBhsmmEz5VGlVVEhqeWdySU0/view?usp=sharing
